### ISSUE TITLE
Install as dynamic library

### ISSUE THREAD

**Issue by nnt296** [open-license-manager/licensecc#132] opened 2021-10-13 10:24 UTC
Hi @gcontini, thanks for the great repository.
Yet, How could I install the `licensecc` as shared object instead of `liblicensecc_static.a`? Since I want to build another shared lib based on your `licensecc`

**Comment by gcontini** [comment] 2021-11-10 02:04
This is a duplicate of #68

**Closed as completed by gcontini** 2021-11-10 02:04 UTC
Labels: duplicate
