### ISSUE TITLE
compile failed on arm linux

### ISSUE THREAD

**Issue by chendd14** [open-license-manager/licensecc#119] opened 2021-02-26 05:51 UTC
licensecc/src/library/os/os-linux.c:216:2: error: impossible constraint in ‘asm’
  __asm __volatile
  
  
How to compile on embedded linu? Has someone tried?

**Comment by gcontini** [comment] 2021-03-04 05:31
duplicate of #83 (sorry arm support isn't planned for now, but if you get it going i'm happy to accept contributions)

**Closed by gcontini** 2021-03-04 05:31 UTC
Labels: duplicate
